FrontProjectInAsp.Net/FrontProjectInAsp.Net/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FrontProjectInAsp.Net.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await (Task.FromResult(View()));
        }
    }
}

FrontProjectInAsp.Net/FrontProjectInAsp.Net/ViewComponents/HeaderViewComponent.cs
using FrontProjectInAsp.Net.Data;
using FrontProjectInAsp.Net.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FrontProjectInAsp.Net.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public HeaderViewComponent(AppDbContext context)
        {
            _context = context;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Catagory> catagories = await _context.Catagories.ToListAsync();

            return await (Task.FromResult(View(catagories)));
        }
    }
}

FrontProjectInAsp.Net/FrontProjectInAsp.Net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="./assets/css/owl.carousel.css">
    <link rel="stylesheet" href="./assets/css/owl.theme.default.css">
    <link rel="stylesheet" href="./assets/css/flipclock.css" />

    <link rel="stylesheet" href="./assets/css/HOME/home2.css">
    <link rel="stylesheet" href="./assets/css/HOME/home.css">
    <link rel="Shortcut Icon" href="https://klbtheme.com/bacola/wp-content/uploads/2021/08/favicon.png"
          type="image/x-icon">
    <link rel="Shortcut Icon" href="https://klbtheme.com/bacola/wp-content/uploads/2021/08/favicon.png"
          type="image/x-icon">
    <title>Bacola</title>
</head>

<body>
    @await Component.InvokeAsync("Header")
    @RenderBody()
    @await Component.InvokeAsync("Footer")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/41137ce79b.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script src="./assets/js/owl.carousel.min.js"></script>
    <script src="./assets/js/flipclock.min.js"></script>
    <script src="./assets/js/homeScript.js"></script>
</body>

</html>